// constants/storage.ts
export const STORAGE_KEYS = {
  SELECTED_BROKER: 'steadfast:broker:selectedId',
  BROKERS: 'brokers',
  LAST_FUNDS: 'lastFunds',
  LAST_USED_AMOUNT: 'lastUsedAmount',
  SELECTED_MULTI_BROKERS: 'steadfast:multitrade:selectedBrokers',
  PRIMARY_BROKER_ID: 'steadfast:primaryBrokerId',
  PRIMARY_BROKER_TYPE: 'steadfast:primaryBrokerType',
  BROKER_ARCHITECTURE: 'steadfast:broker:architecture',
  TRADE_SELECTED_SEGMENT: 'steadfast:trade:selectedSegment',
  TRADE_SELECTED_EXCHANGE: 'steadfast:trade:selectedExchange',
  TRADE_SELECTED_SYMBOL: 'steadfast:trade:selectedSymbol',
  TRADE_PRODUCT_TYPE: 'steadfast:trade:selectedProductType',
  TRADE_ORDER_TYPE: 'steadfast:trade:selectedOrderType',
  TRADE_SHORTCUTS_ENABLED: 'steadfast:trade:shortcutsEnabled',
  TRADE_STOPLOSS_ENABLED: 'steadfast:trade:stopLossEnabled',
  TRADE_TARGET_ENABLED: 'steadfast:trade:targetEnabled',
  EXPIRY_OFFSET: 'steadfast:trade:expiryOffset',
  CALL_STRIKE_OFFSET: 'steadfast:trade:callStrikeOffset',
  PUT_STRIKE_OFFSET: 'steadfast:trade:putStrikeOffset',
  DEFAULT_STOPLOSS: 'steadfast:trade:defaultStopLoss',
  DEFAULT_TARGET: 'steadfast:trade:defaultTarget',
  POSITION_TRIGGERS: 'steadfast:position_triggers',
}
